### ISSUE TITLE
To-Do List 

### ISSUE THREAD

**Issue by prodigyinfotech** [Prodigy-InfoTech/Web-Development-Projects#11]
Create a task management web app where users can add, edit, and delete tasks.

**Comment by harishghasolia07** [comment]
Can I work on this?

**Comment by ShreyasThakur0809** [comment]
I would like to work on this.

**Comment by prodigyinfotech** [comment]
Hey @harishghasolia07 you have been assigned.

@ShreyasThakur0809 & @soumyadeeproychowdhury Only one issue at a time is allowed

**Comment by Pranav2112** [comment]
Hey @prodigyinfotech 
I'm ready to work on this issue
Can you assign it to me..?
