### ISSUE TITLE
Weather Teller

### ISSUE THREAD

**Issue by prodigyinfotech** [Prodigy-InfoTech/Web-Development-Projects#12]
Build a weather web app that allows users to enter a location and get current weather information. You can use a weather API to fetch data.

**Comment by Neerajmeka25** [comment]
Hey @prodigyinfotech,
Can you assign me

**Comment by classmate692** [comment]
Hello, I would like to work on this project.

**Comment by tejus05** [comment]
hey! please assign this to me, i've already worked on it
