### ISSUE TITLE
🚀 Project: Text Generator

### ISSUE THREAD

**Issue by Recdata** [Prodigy-InfoTech/Web-Development-Projects#121]
### 🔖 Project description

Text Generator is a versatile and user-friendly web application designed to generate dummy text quickly and efficiently. It provides users with the ability to input a desired number between 1 to 50 and receive a corresponding amount of sections containing dummy text. This project aims to streamline the process of generating placeholder text for various purposes such as web development, graphic design, content creation, and more.

### 🎤 Pitch

This project will help developers to have in-built tool for generating unlimited amount of dummy text. It will save time for them to not dodge upon different online tools instead of having their own tool for generating text for their projects.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Prodigy-InfoTech/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Recdata** [comment]
Please Assign me this task.

**Comment by scifisatan** [comment]
Can i do this?
