### ISSUE TITLE
Landing page for a product or service

### ISSUE THREAD

**Issue by prodigyinfotech** [Prodigy-InfoTech/Web-Development-Projects#14]
Design a responsive single-page website that is designed to promote a specific product or service.

**Comment by Neerajmeka25** [comment]
Hey @prodigyinfotech,
Can you assign me

**Comment by soumyadeeproychowdhury** [comment]
Hi! Could you assign me this would love working on it!

**Comment by Upendra2003** [comment]
Can u assign me this I can do this .. @prodigyinfotech

**Comment by prodigyinfotech** [comment]
Hey @Neerajmeka25 we have assigned you the issue

**Comment by Neerajmeka25** [comment]
Hey @prodigyinfotech,
I have completed the project. Kindly review it
