### ISSUE TITLE
Music Player

### ISSUE THREAD

**Issue by prodigyinfotech** [Prodigy-InfoTech/Web-Development-Projects#15]
Develop a simple online music player where users can upload and play their music files.

**Comment by soumyadeeproychowdhury** [comment]
Hi! could I be assigned this issue would love working on it!

**Comment by BHS-Harish** [comment]
Hey @prodigyinfotech 

Can you assign it to me..?

Thanks in advance

**Comment by classmate692** [comment]
Hello, I would like to work on this project.
