### ISSUE TITLE
🚀 Project: chrome extension to help ui designers

### ISSUE THREAD

**Issue by Ayush-Dhawan** [Prodigy-InfoTech/Web-Development-Projects#167]
### 🔖 Project description

Building a shade selector which can be added as a chrome extension enabling people to easily select similar shades to colours of their choice without the hassle of managing multiple tabs for a color picker.

### 🎤 Pitch

The project solves a real life problem faced by me and a few colleagues when working on designs where we have to take unnecessary efforts for arranging color shades which is distracting and also tiring. This project will enable users to focus more on design and less on hassel

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Prodigy-InfoTech/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Ayush-Dhawan** [comment]
I would like to work on the issue @prodigyinfotech

**Comment by prodigyinfotech** [comment]
Please pitch it under Software Development
