### ISSUE TITLE
Resume Builder

### ISSUE THREAD

**Issue by prodigyinfotech** [Prodigy-InfoTech/Web-Development-Projects#176]
Build a platform that allows users to build a resume/CV by simply entering their educational details, experience, skills, achievements, etc. and can download it as PDF.

**Comment by yashwanthvarma18** [comment]
Hey @prodigyinfotech  I believe I can complete the task you require.Please assign it to me
Thank you!

**Comment by yashwanthvarma18** [comment]
@prodigyinfotech can you please check my PR and merge it

**Comment by yashwanthvarma18** [comment]
@prodigyinfotech Please merge my PR
