### ISSUE TITLE
Create Tic-Tac-Toe Game

### ISSUE THREAD

**Issue by prodigyinfotech** [Prodigy-InfoTech/Web-Development-Projects#2]
Develop a multiplayer Tic-Tac-Toe game with a responsive user interface.

**Comment by ShreyasThakur0809** [comment]
Hello, I would like to work on this project.

**Comment by prodigyinfotech** [comment]
Hey @ShreyasThakur0809 we have assigned you the issue.
You can start working on it.

**Comment by soumyadeeproychowdhury** [comment]
Hi! Could you assign me this would love working on it!
