### ISSUE TITLE
Countdown Timer Website

### ISSUE THREAD

**Issue by prodigyinfotech** [Prodigy-InfoTech/Web-Development-Projects#23]
Create a countdown timer website. Contributors can customize the timer's appearance, add sound effects, or implement event triggers.

**Comment by Janhavi30052002** [comment]
!assign

**Comment by Git0Chetan** [comment]
I would like to work on these project.
 I have created the same project earlier also.
you can see the sample below:

# Countdown
<img width="1440" alt="CountDown" src="https://github.com/Prodigy-InfoTech/Web-Development-Projects/assets/123874710/6c988d39-de70-4d86-a6d2-5602b527425b">

**Comment by Parmesh119** [comment]
Hi @prodigyinfotech, I am Parmesh Bhatt.
I hope you are fine.
Can you assign this issue to me?

**Comment by Subrat29** [comment]
Hello,

I'd like to work on this issue. Could you please assign it to me?

Thank you,
Subrat

**Comment by Git0Chetan** [comment]
Hello @prodigyinfotech , I was watching from past 3 weeks , these issue was not closed , so I have made the project and Requested a PR, Please Review it and Merge.
Thank You.
