### ISSUE TITLE
Currency Converter Website

### ISSUE THREAD

**Issue by prodigyinfotech** [Prodigy-InfoTech/Web-Development-Projects#24]
Build a simple currency converter website. Contributors can also add more currency options and improve the exchange rate accuracy.

**Comment by avyuktsoni0731** [comment]
Hi @prodigyinfotech . I would love to work on this issue. Can you please assign this to me?

Thanks :)

**Comment by Parmesh119** [comment]
Hi @avyuktsoni0731, I am Parmesh Bhatt.
I hope you are fine.
Can I also solve this problem?
