### ISSUE TITLE
Develop Math Calculator

### ISSUE THREAD

**Issue by prodigyinfotech** [Prodigy-InfoTech/Web-Development-Projects#3]
Build a web-based calculator that performs basic mathematical operations (addition, subtraction, multiplication, division).

**Comment by Manavr472** [comment]
Hello, I would like to work on this issue.

**Comment by prodigyinfotech** [comment]
Hey @Manavr472  we have assigned you the issue.
You can start working on it.

**Comment by gauravpatil97886** [comment]
Hey, can I work on this issue?

**Comment by prodigyinfotech** [comment]
Hey @gauravpatil97886,

It has been already assigned. You can open request for new projects to get them assigned to you.

**Comment by NilanjanPramanik** [comment]
@prodigyinfotech Hello sir I have raised a PR kindly check it..
