### ISSUE TITLE
🚀 Project: Counter Application

### ISSUE THREAD

**Issue by serhatbek** [Prodigy-InfoTech/Web-Development-Projects#43]
### 🔖 Project description

If possible, I want to build a counter app that allows you to increase, decrease, and reset a counter value.

### 🎤 Pitch

I'll build it using HTML, CSS, and JavaScript.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Prodigy-InfoTech/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by serhatbek** [comment]
@prodigyinfotech , please excuse me for my confusion, should I re-fork and add the project again or the problem is solved?

**Comment by prodigyinfotech** [comment]
it has been accepted. No changes are required
