### ISSUE TITLE
URL Shortener

### ISSUE THREAD

**Issue by prodigyinfotech** [Prodigy-InfoTech/Web-Development-Projects#44]
Develop a web-based URL shortening service that takes long URLs and converts them into shorter, more manageable links. Users can then share these shortened links, and when others click on them, they are redirected to the original long URL.

**Comment by Cstrp** [comment]
U can assigned it for me.

**Comment by SurajPrakash24** [comment]
Can you please assign to me. I would love to work on this project

**Comment by prabincankod** [comment]
@prodigyinfotech please review 
Refs. #51

**Comment by SurajPrakash24** [comment]
@prodigyinfotech Can you please assign this issue?

**Comment by prabincankod** [comment]
@prodigyinfotech thanks
