### ISSUE TITLE
Currency converter

### ISSUE THREAD

**Issue by prodigyinfotech** [Prodigy-InfoTech/Web-Development-Projects#7]
This is a web application that converts one currency to another.

**Comment by ishan-nahid** [comment]
Can you assign me?

**Comment by soumyadeeproychowdhury** [comment]
Hi! Could you assign me this would love working on it!

**Comment by prodigyinfotech** [comment]
Hey @ishan-nahid,

We have assigned you the issue. You can Start working on it

**Comment by ishan-nahid** [comment]
now you can review and marge.
