### ISSUE TITLE
Gradient Color Picker 🚀 Project: 

### ISSUE THREAD

**Issue by Rahul-Bhati** [Prodigy-InfoTech/Web-Development-Projects#71]
### 🔖 Project description

I would like attach my gradient color picker project under **Hacktoberfest** that i recently completed.

### 🎤 Pitch

It is implemented using html, css and javascript

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Prodigy-InfoTech/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by prodigyinfotech** [comment]
You can start working on it
