### ISSUE TITLE
🚀 Project: Guessing game

### ISSUE THREAD

**Issue by TanvNaik** [Prodigy-InfoTech/Web-Development-Projects#77]
### 🔖 Project description

This application is a number guessing game where users are allowed to make guesses to see if how many tries it takes them to get the correct number. Their game score will be equal to the amount of attempts. The user will get hints such as the guessed number is too high, too low, etc.

### 🎤 Pitch

This project was developed with Javascript, HTML, and CSS.  It is a good project for beginners as it includes usage of DOM, javascript functions and basic CSS styling.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Prodigy-InfoTech/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by ishan-nahid** [comment]
assign it to me.

**Comment by ishan-nahid** [comment]
@TanvNaik check and let me know.

**Comment by ishan-nahid** [comment]
add hacktoberfest-accepted label

**Comment by ishan-nahid** [comment]
check and add hacktoberfest-accepted label
