### ISSUE TITLE
BMI calculator

### ISSUE THREAD

**Issue by prodigyinfotech** [Prodigy-InfoTech/Web-Development-Projects#8]
Build a web application that calculates a person's body mass index (BMI).

**Comment by SaiganeshGurrapu16** [comment]
I am new to open source, I want to work on this issue. Can you assign this to me.

**Comment by soumyadeeproychowdhury** [comment]
Hi! Could you assign me this would love working on it!

**Comment by Upendra2003** [comment]
Can u assign me this I'd love to do this.. @prodigyinfotech

**Comment by prodigyinfotech** [comment]
Hey @Upendra2003,
we have assigned you the issue. You can start working on it.
