### ISSUE TITLE
🚀 Project: Quizzeria

### ISSUE THREAD

**Issue by TanvNaik** [Prodigy-InfoTech/Web-Development-Projects#81]
### 🔖 Project description

# Quizzeria
##### This web application displays 5 random questions with their options and 	on clicking the submit button it displays our score out of 5 . "Play again" button displays another set of 5 random questions.

-  I have stored my questions in data.js file which exports 5 questions.
- I have also created QuestionBox component to display a question along with its options.

 [Live Demo](https://tanvnaik.github.io/react-quiz-app/ "Live Demo")

### 🎤 Pitch

This project was developed with Reactjs, HTML, and CSS. It is a good project for beginners as it includes usage of DOM, javascript functions, reactjs and basic CSS styling.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Prodigy-InfoTech/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by prodigyinfotech** [comment]
Issue already exists and has been assigned to someone else.
