### ISSUE TITLE
🚀 Project: Login Page

### ISSUE THREAD

**Issue by rhnas110** [Prodigy-InfoTech/Web-Development-Projects#95]
### 🔖 Project description

Project simple login page using html css, there is email input and password input with show hide password eye icon, and maybe a simple button for third party login such as apple, google, facebook.

### 🎤 Pitch

Because I saw that there is no project or issue about the login page, so I really want to contribute this issue.
How I implemented it:
- I created a new folder for this issue named Login Page,
- I created a simple structure for the files in the Login Page folder, there is index.html, style.css and an assets folder for images if needed
- and Happy Coding🧑🏻‍💻

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Prodigy-InfoTech/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by priyanshu-gupta0503** [comment]
hey@prodigyinfotech  I would like to work on this project pls assign this issue to me

**Comment by rhnas110** [comment]
Thank you for your response Sir @prodigyinfotech , and assigning this task to me. I am new to open source contributions and I would love to contribute to your project! I also participated in Hacktoberfest2023.

**Comment by urvashi-2004** [comment]
@prodigyinfotech I'd like to do this project.
